ROLE_PERMISSIONS: dict[str, set[str]] = {
    "analista": {
        "consultar_cliente",
        "evaluar_oferta",
        "consultar_evaluacion",
        "registrar_solicitud",
        "consultar_solicitud",
        "anular_solicitud",
        "exportar_bandeja",
        "gestionar_adjuntos",
        "explicar_evaluacion_ai",
    },
    "evaluador": {
        "consultar_cliente",
        "evaluar_oferta",
        "consultar_evaluacion",
        "consultar_trace",
        "consultar_solicitud",
        "anular_solicitud",
        "cambiar_estado_solicitud",
        "exportar_bandeja",
        "gestionar_adjuntos",
        "explicar_evaluacion_ai",
    },
    "supervisor": {
        "consultar_cliente",
        "evaluar_oferta",
        "consultar_evaluacion",
        "consultar_trace",
        "registrar_solicitud",
        "consultar_solicitud",
        "anular_solicitud",
        "cambiar_estado_solicitud",
        "exportar_bandeja",
        "gestionar_adjuntos",
        "consultar_resumen_ai",
        "explicar_evaluacion_ai",
        "consultar_auditoria",
    },
    "auditor": {
        "consultar_evaluacion",
        "consultar_trace",
        "consultar_solicitud",
        "consultar_auditoria",
    },
    "admin_negocio": {
        "administrar_productos",
        "administrar_workflows",
        "administrar_variables",
        "administrar_catalogos_variables",
        "solicitar_versionado_motor",
        "consultar_bloqueos_activacion",
        "consultar_auditoria",
    },
    "admin_riesgos": {
        "administrar_reglas",
        "administrar_parametros",
        "administrar_pipeline",
        "administrar_origenes_variables",
        "aprobar_activacion_motor",
        "consultar_bloqueos_activacion",
        "consultar_auditoria",
    },
    "admin_plataforma": {
        "administrar_usuarios",
        "consultar_auditoria",
    },
    "admin": {
        "consultar_cliente",
        "evaluar_oferta",
        "consultar_evaluacion",
        "consultar_trace",
        "registrar_solicitud",
        "consultar_solicitud",
        "anular_solicitud",
        "cambiar_estado_solicitud",
        "exportar_bandeja",
        "gestionar_adjuntos",
        "consultar_resumen_ai",
        "explicar_evaluacion_ai",
        "administrar_reglas",
        "administrar_pipeline",
        "administrar_parametros",
        "administrar_usuarios",
        "administrar_productos",
        "administrar_workflows",
        "administrar_variables",
        "administrar_catalogos_variables",
        "administrar_origenes_variables",
        "aprobar_activacion_motor",
        "solicitar_versionado_motor",
        "consultar_bloqueos_activacion",
        "consultar_auditoria",
    },
}


def roles_grant_permission(user_roles: list[str], permission: str) -> bool:
    return any(permission in ROLE_PERMISSIONS.get(role, set()) for role in user_roles)
